### ISSUE TITLE
Host project without Node JS server

### ISSUE THREAD

**Issue by afonsosantos** [arifszn/ezfolio#4]
Hi.

First, thank you for this awsome project!
My question is, how could we run this app without Node JS? I have a PHP hosting space, but the Node JS part is not very well supported.

Thanks!

**Comment by arifszn** [comment]
Thanks for your interest in this project. If your server is not node friendly, you can try the following options:

- First host this project on Github page(Recommended). Then add a custom domain pointing to your domain. You may need to add an entry in your server's Zone Editor. There are some great articles on the internet about it, but if you need help, simply reply here.

- The second one is to change the homepage of the project to your domain name. Then build it, zip it locally. And finally, upload the zip file to your server and extract it.

You may check out my other portfolio project [Ezfolio](https://github.com/arifszn/ezfolio) which is built for PHP server.

**Comment by arifszn** [comment]
Thanks for your interest in this project. You don't need actually node.js in the server to host. I am guessing you have shared hosting. Follow these steps for shared hosting.
- Build the project locally by following [the guide](https://github.com/arifszn/ezfolio#installation).
- Zip the project.
- Upload to your server and then extract it.
- Provide database info in .env
- Then you need to migrate and seed data. If you are unable to run <code>php artisan migrate --seed</code> or any artisan command in your shared hosting, you can run the command in the browser. The URL is: <code>yourdomain.com/command/</code>. Migration command would look like <code>yourdomain.com/command/migrate --seed</code>.Make sure <code>APP_ENV</code> is set to local in .env file.

Also, go through the [FAQ section](https://arifszn.github.io/ezfolio/docs/faq).

If you are lost in any step or face any problem, do reply here. I will try my best to assist you.
