### ISSUE TITLE
Running migrations error 'No such file or directory' - with Docker, locally

### ISSUE THREAD

**Issue by alexpppp** [arifszn/ezfolio#8]
G'day, 

Looks like a great codebase! I was having a crack at running it locally to take it for a spin and have been stuck on an error when running migrations.

I'm running this locally, and following the 'With Docker' steps.

When I get down to running bullet point 4:
`./vendor/bin/sail artisan migrate --seed`

it gives me the error 
`SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = ezfolio and table_name = migrations and table_type = 'BASE TABLE')`

And if I change the env var DB_HOST to be 'localhost' (as suggested by several stackOverflow articles) I get
`SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from information_schema.tables where table_schema = ezfolio and table_name = migrations and table_type = 'BASE TABLE')`

I've also been clear config cache, and removing any other docker containers and volumes just in case they were interfering, but no change. Is there an obvious step that isn't documented that I could be missing?

**Comment by arifszn** [comment]
Thanks for taking interest in this project.

Can you change the `DB_HOST` of env to `mysql` and let me know if it works?(`DB_HOST=mysql`)

**Comment by alexpppp** [comment]
Ah yep that did it thanks! All running nicely now =)

Cheers for the prompt reply, will have a dig around now...

**Comment by afonsosantos** [comment]
Hi there,
Same issue here, changed the `DB_HOST `variable to `mysql`. but same error.
